/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yazlab2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Eliz
 */
public class Grafik extends javax.swing.JFrame {

    private double width;
    private double height;
    private static int sayi;
    private static String s;
    private static String s1;
    /**
     * Creates new form Grafik
     */
    public Grafik(String s,String s1) {
        this.s=s;
        this.s1=s1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafik(s,s1).setVisible(false);
            }
        });
    }
    
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d =(Graphics2D) g;
        
        width=getWidth();
        height=getHeight();
        
        g2d.setPaint(Color.BLACK);
        g2d.drawLine(0, (int) (height-100), (int)(width), (int)(height-100)); //yatay
        g2d.drawLine(100, 0, 100, (int)(height)); //dikey
        g2d.drawLine(150, (int) (height-100), 150, (int) (height-105));//xdeki noktalar
        g.drawString("0.1", 150, (int) (height-85));
        g2d.drawLine(200, (int) (height-100), 200, (int) (height-105));
        g.drawString("0.2", 200, (int) (height-85));
        g2d.drawLine(250, (int) (height-100), 250, (int) (height-105));
        g.drawString("0.3", 250, (int) (height-85));
        g2d.drawLine(300, (int) (height-100), 300, (int) (height-105));
        g.drawString("0.4", 300, (int) (height-85));
        g2d.drawLine(350, (int) (height-100), 350, (int) (height-105));
        g.drawString("0.5", 350, (int) (height-85));
        g2d.drawLine(400, (int) (height-100), 400, (int) (height-105));
        g.drawString("0.6", 400, (int) (height-85));
        g2d.drawLine(450, (int) (height-100), 450, (int) (height-105));
        g.drawString("0.7", 450, (int) (height-85));
        g2d.drawLine(500, (int) (height-100), 500, (int) (height-105));
        g.drawString("0.8", 500, (int) (height-85));
        g2d.drawLine(550, (int) (height-100), 550, (int) (height-105));
        g.drawString("0.9", 550, (int) (height-85));
        g2d.drawLine(600, (int) (height-100), 600, (int) (height-105));
        g.drawString("1", 600, (int) (height-85));
        
        g2d.drawLine(100,(int) (height-450) ,105, (int) (height-450));//y noktası
        g.drawString("248", 75, (int) (height-450));
        
        g.drawString("milisaniye", (int)(width-80), (int) (height-85));
        g.drawString("cozulen kutu sayisi", 55, (int) (height-550));
        g.drawString("Yesil - 5thread", 650, 100);
        g.drawString("Turuncu - 10thread", 650, 130);
        
        int sayi=Character.getNumericValue(s.charAt(0));
        g2d.setColor(Color.GREEN);
        if(sayi==5)
        {
         g2d.drawLine(100, (int) (height-100), 350, (int) (height-450));
        }else if(sayi==6){
            g2d.drawLine(100, (int) (height-100), 400, (int) (height-450));
        }else if(sayi==7){
            g2d.drawLine(100, (int) (height-100), 450, (int) (height-450));
        }else if(sayi==8){
            g2d.drawLine(100, (int) (height-100), 500, (int) (height-450));
        }else if(sayi==9){
            g2d.drawLine(100, (int) (height-100), 550, (int) (height-450));
        }else if(sayi==1){
            g2d.drawLine(100, (int) (height-100), 600, (int) (height-450));
        }
        
        int sayi1=Character.getNumericValue(s1.charAt(0));
        g2d.setColor(Color.ORANGE);
        if(sayi1==5)
        {
         g2d.drawLine(100, (int) (height-100), 350, (int) (height-450));
        }else if(sayi1==6){
            g2d.drawLine(100, (int) (height-100), 400, (int) (height-450));
        }else if(sayi1==7){
            g2d.drawLine(100, (int) (height-100), 450, (int) (height-450));
        }else if(sayi1==8){
            g2d.drawLine(100, (int) (height-100), 500, (int) (height-450));
        }else if(sayi1==9){
            g2d.drawLine(100, (int) (height-100), 550, (int) (height-450));
        }else if(sayi1==1){
            g2d.drawLine(100, (int) (height-100), 600, (int) (height-450));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
